# Dependabot Security Updates Configuration
# It ensures dependencies are automated updated to stays secure through automated PRs

version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    # Check for updates daily to ensure quick response to security issues
    schedule:
      interval: 'daily'
    # Limit the number of concurrent PRs to avoid overwhelming the repository
    open-pull-requests-limit: 10
    # Apply these labels to all PRs for easier filtering and automation
    labels:
      - 'dependencies'
    # Assign the repository owner for review
    reviewers:
      - 'essomia'
    # Only create PRs for security-related updates to minimize noise
    allow:
      - dependency-type: 'all'
        update-type: 'security'
    # Enable scanning and alerts for security vulnerabilities
    vulnerability-alerts: true
    # Automatically merge security updates when possible to reduce manual intervention
    auto-merge: true
